var msg = [
    "this is the first ever message",
    "testing testing 123",
    "made with 0% beef",
    "cheborger",
    "...",
    "idk what to put here",
    "this message is a referance to among us",
    "snickers bars = tasty",
    "whopper whopper whopper whopper jr. double triple whopper flamegrilled taste with perfect toppers i rule this day, lettuce mayo pick ketchu- ok this is way too long",
    "dGhlcmUgaXMgYSBkaXNjb3JkIHNlcnZlciBmb3IgbXkgd2Vic2l0ZQ==",
    "amuug",
    "hi",
    "baba",
    "why are chairs at school kinda comfy",
    "error 408: george not found",
    "redwoodsteve on youtube :)",
    ":0",
    ">:0",
    ">;}",
    "\'(^ . ^)'/ meow",
    "cats or dogs",
    "artclass.lol is a unofficial copy of artclass.site",
    "someone cloned my website at Roy Cloud (they are worthless)",
    "dont translate 'is' into luxembourgish",
    "li|",
    "<>{}[]()''``",
    "securly and blocksi are terrible",
    "play games in class at your own risk",
    "you are a 10/10 gigachad",
    "what is bro up to",
    "i learned how to code from W3schools, MDN web docs, and a book called 'JavaScript and AJAX for dummies'",
    "i like coding",
    "the more messages, the less chance to get one of these messages, so count yourself lucky",
    "'Spacewar! is a space combat video game developed in 1962 by Steve Russell in collaboration with Martin Graetz, Wayne Wiitanen, Bob Saunders, Steve Piner, and others. The first video game known to be played at multiple computer installations, it was popular in the small American programming community in the 1960s. Players wage a dogfight between two spaceships with limited weaponry and fuel in the gravity well of a star. Spacewar! was written for the newly installed Digital Equipment PDP-1, a minicomputer, at the Massachusetts Institute of Technology, and the public domain code was widely ported. Saunders built an early gamepad controller for the game. It directly inspired many electronic games, such as the first commercial arcade video games, Galaxy Game and Computer Space (both 1971), and later games such as Asteroids (1979). In 2007, Spacewar! was named to a list of the ten most important video games of all time, which formed the start of the game canon at the Library of Congress.' -wikipedia.org",
    "some of these messages are very, very long",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "no",
    "snow",
    "the minecraft create mod is cool",
    "minecraft > roblox > fortnite",
    "'is your tabatry clean?' - one of my fellow comrades",
    "inspired by artclass",
    "192.168.30.76",
    "i know were u live",
    "",
    "cocomelon is very.. umm..",
    "good message",
    "bad message",
    "'Psyche (/ˈsaɪkiː/) is a NASA space mission launched on October 13, 2023 to explore the origin of planetary cores by orbiting and studying the metallic asteroid 16 Psyche.[8] NASA's Jet Propulsion Laboratory (JPL) manages the project.16 Psyche is the heaviest known M-type asteroid, and may be an exposed iron core of a protoplanet, the remnant of a violent collision with another object that stripped off its mantle and crust. On January 4, 2017, the Psyche mission was selected for NASA's Discovery #14 mission.[9] It was launched atop a SpaceX Falcon Heavy rocket.[10]' -Wikipedia.org",
    ",",
    "hello world",
    "hi from mo",
    "i liek chez",
    "you are probably wasting your time going through these messages",
    "my friend's hand = broken :(",
    "lorem ispum dolar sit amet",
    "amungsters",
    "HALOWEN",
    "redwoodsteve on discord",
    "beam be up scotty",
    "its honest work",
    "much dogecoin",
    "breath air",
    "ohio :0",
    "i dont like homework :(",
    "UWU",
    "OWO",
    "this message is on line 69 of my code",
    "'The mistletoebird (Dicaeum hirundinaceum), also known as the mistletoe flowerpecker, is a species of flowerpecker native to most of Australia (though absent from Tasmania and the driest desert areas) and also to the eastern Maluku Islands of Indonesia in the Arafura Sea between Australia and New Guinea. The mistletoebird eats mainly the berries of the parasitic mistletoe and is a vector for the spread of the mistletoe's seeds through its digestive system. The mistletoebird is small, being 9–10 centimetres long and 7.5–11 grams in weight. The male is glossy blue-black above, with a red chest and a slight red under-tail, and a black centre stripe running down its white belly. The female is dark grey above, with a white throat, light grey underparts, and just a touch of pinkish-red under the tail. The eyes, bill, and legs are black; the bill is just over a centimetre long, slender, slightly down-curved and sharply pointed. Immature birds are similar to the female, but have an orange-pink bill instead of black. This male mistletoebird was photographed in the Round Hill Nature Reserve in New South Wales, Australia.' -wikipedia.org",
    "this website is to not be abused",
    "did you know that a gallon of average gasoline has about 31,000 calories",
    "did you know that hot water turns into ice faster than cold water? this is because hot water evaporates faster than cold water, meaning its volume is lower. the lower volume of hot water makes if freeze faster.",
    "its actually impossible to lick your own elbow",
    "sneezing too hard might make you fracture a rib..",
    "did you know that cat urine glows under a blacklight",
    "did you know a shark is the only known fish that can blink with both eyes",
    "the only english words that end with 'mt' are 'dreamt' and its variations",
    "the full name of Los Angeles is 'El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula'",
    "a cat has 32 muscles in each ear",
    "the eye of an ostrich is bigger than it's brain",
    "in a lot of ads, the time displayed on a watch is 10:10",
    "a dime has 118 ridges around its edge",
    "the average human falls asleep in seven minutes",
    "almonds actually belong to the peach family",
    "boeing also produces satellites",
    "boeing is the largest aircraft company",
    "the airbus A380 is the largest passenger airliner",
    "the antonov AN225 is the biggest airplane ever, but it only transported cargo. it got bombed during the war involving Russia and Ukraine.",
    "i liek airplanes",
    "ai is smart",
    "you can order a commercial airliner",
    "you can (probably) order a fighter jet (they are not cheap)",
    "airliners fly on specified routes, they only deviate from the planned path to avoid risks like storms",
    "turbulence never crashed an airplane, it only hurt someone when they were not buckled in to their seat",
    "money is dirty",
    "the averge person eats 10 spiders during their sleep in their lifetime (oohh spooky)",
    "this letter is very small: י",
    "99 bottles of beer on the wall",
    "100",
    "before a new airliner can be used for commercial or cargo use, it must be able to stay in flight for another 70 miles when both engines are lost.",
    "this is the 100th message",
    "Wafflqs",
    "the boeing 777 has the most powerfull engines of any airliner",
    "hi from alex",
    "shoe",
    "python is not used in websites (most of the time)",
    "GYATTTTTT",
    "bluemoji",
    "'play hollowknight' - maxim",
    "you are awesome!",
    "vsauce, michal here. you can't get this message.. or can you?",
    "take me to your xbox to play minecraft today",
    "heres a random number from 0 to 1: " + Math.random(),
    "this will open google.com" + window.open("https://google.com"),
    "lol"
]