var msg = [
    "this is the first ever message",
    "testing testing 123",
    "made with 0% beef",
    "cheborger",
    "...",
    "idk what to put here",
    "this message is a referance to among us",
    "snickers bars = tasty",
    "whopper whopper whopper whopper jr. double triple whopper flamegrilled taste with perfect toppers i rule this day, lettuce mayo pick ketchu- ok this is way too long",
    "dGhlcmUgaXMgYSBkaXNjb3JkIHNlcnZlciBmb3IgbXkgd2Vic2l0ZQ==",
    "amuug",
    "hi",
    "baba",
    "why are chairs at school kinda comfy",
    "error 408: george not found",
    "redwoodsteve on youtube :)",
    ":0",
    ">:0",
    ">;}",
    "\'(^ . ^)'/ meow",
    "cats or dogs",
    "artclass.lol is a unofficial copy of artclass.site",
    "someone cloned my website at Roy Cloud (they are worthless)",
    "dont translate 'is' into luxembourgish",
    "li|",
    "<>{}[]()''``",
    "securly and blocksi are terrible",
    "play games in class at your own risk",
    "you are a 10/10 gigachad",
    "what is bro up to",
    "i learned how to code from W3schools, MDN web docs, and a book called 'JavaScript and AJAX for dummies'",
    "i like coding"
]